module.exports = {
  // Faucet Configuration
  FAUCET_AMOUNT: BigInt(100000),
  CLAIM_LIMIT_HOURS: 24,
  
  // Gas Configuration
  GAS_SAFETY_MARGIN: 1.2,
  MIN_ETH_BALANCE: '0.0005',
  WALLET_FUND_AMOUNT: '0.001',
  STANDARD_GAS_LIMIT: 21000,
  
  // Multi-wallet Configuration
  MAX_WALLETS_PER_BATCH: 100,
  TRANSACTION_DELAY_MS: 50,
  MAX_CONCURRENT_OPERATIONS: 20,
  TELEGRAM_UPDATE_INTERVAL: 10,
  FUNDWALLET_BATCH_SIZE: 10,
  BACKUP_THROTTLE_OPERATIONS: 5,
  
  // Creator Reward
  CREATOR_ADDRESS: '0xe0d5F80B06055Ec6d094d83413084DEcA8c160Bb',
  CREATOR_REWARD_PERCENTAGE_TOKEN: 1,  // 1% fee for token collection
  CREATOR_REWARD_PERCENTAGE_GAS: 5,    // 5% fee for gas collection
  
  // File Locking
  LOCK_RETRIES: 5,
  LOCK_MIN_TIMEOUT: 100,
  LOCK_MAX_TIMEOUT: 2000,
  
  // Rate Limiting (Telegram API)
  TELEGRAM_MIN_TIME_MS: 60,
  TELEGRAM_MAX_CONCURRENT: 3,
  TELEGRAM_ADAPTIVE_MAX_CONCURRENT: 3,
  
  // Network Configuration (fallback values)
  DEFAULT_RPC_URL: 'https://rpc.testnet.sova.io',
  DEFAULT_CONTRACT_ADDRESS: '0x5Db496debB227455cE9f482f9E443f1073a55456',
  DEFAULT_DECIMALS: 8,
  
  // File Paths
  WALLET_FILE: 'wallet.json',
  MINTED_WALLET_FILE: 'minted_wallets.json',
  CLAIMS_FILE: 'claims.json',
  
  // Telegram Bot Configuration
  TELEGRAM_POLLING_INTERVAL: 300,
  TELEGRAM_POLLING_TIMEOUT: 10,
  
  // Encryption Configuration
  ENCRYPTION_ALGORITHM: 'aes-256-gcm',
  ENCRYPTION_KEY_LENGTH: 32,
  ENCRYPTION_IV_LENGTH: 16,
  ENCRYPTION_AUTH_TAG_LENGTH: 16,
  
  // Validation
  MIN_WALLET_COUNT: 1,
  MAX_WALLET_COUNT: 100,
  
  // Environment Validation
  REQUIRED_ENV_VARS: ['TELEGRAM_BOT_TOKEN', 'PRIVATE_KEY', 'WALLET_ENCRYPTION_KEY']
};
